

* Documentation

[[http://nomads.ncdc.noaa.gov/docs/ncdc-narrdsi-6175-final.pdf][National Climatic Data Center Data Documentation]]

* Idenitfy which files we need

Some files on the [[ftp://nomads.ncdc.noaa.gov/NARR/][NARR section of the NOMADS FTP server]] appear to be
redundant so do a checksum comparison to be sure that there is no
difference.

#+begin_src sh :results output verbatim :session *shell* :cache yes
  wget --timestamping --force-directories --no-host-directories --directory-prefix data --cut-dirs=2 --no-verbose \
      http://nomads.ncdc.noaa.gov/data/narr/197901/19790101/narr-a_221_19790101_0000_000.grb
  wget --timestamping --force-directories --no-host-directories --directory-prefix data --cut-dirs=2 --no-verbose \
      http://nomads.ncdc.noaa.gov/data/narr/197901/197901/narr-a_221_19790101_0000_000.grb
#+end_src

#+RESULTS[d87f219f1d8606b95ad980e6ca8464caae0d5172]:
: 
: 2012-11-15 13:05:30 URL:http://nomads.ncdc.noaa.gov/data/narr/197901/19790101/narr-a_221_19790101_0000_000.grb [56399426/56399426] -> "data/197901/19790101/narr-a_221_19790101_0000_000.grb" [1]
: > 2012-11-15 13:05:42 URL:http://nomads.ncdc.noaa.gov/data/narr/197901/197901/narr-a_221_19790101_0000_000.grb [56399426/56399426] -> "data/197901/197901/narr-a_221_19790101_0000_000.grb" [1]

#+BEGIN_SRC sh :results output verbatim :session *shell*
  find data -name narr-a_221_19790101_0000_000.grb -exec md5sum \{\} \;
#+END_SRC

#+RESULTS:
: 3551e6ff8bf9896f1fbabf37a2613f54  data/197901/197901/narr-a_221_19790101_0000_000.grb
: 3551e6ff8bf9896f1fbabf37a2613f54  data/197901/19790101/narr-a_221_19790101_0000_000.grb

Now we can be reasonably sure that it doesn't matter what directory we take the data from.


* Download the data

Compose the URLs.

#+BEGIN_SRC R :session *R* :results silent
  baseUrl <- "ftp://nomads.ncdc.noaa.gov/NARR"
  
  narrMonths <-
    seq(
      as.Date( "1979-01-01"),
      as.Date( "2012-11-01"),
      by= "month")
  
  urls <- paste(
    baseUrl,
    format( narrMonths, "%Y%m"),
    format( narrMonths, "%Y%m"),
    sep= "/")
#+END_SRC

Examine a sample of the resulting URLs.

#+BEGIN_SRC R :session *R*
  head( urls)
#+END_SRC

#+RESULTS:
| ftp://nomads.ncdc.noaa.gov/NARR/197901/197901 |
| ftp://nomads.ncdc.noaa.gov/NARR/197902/197902 |
| ftp://nomads.ncdc.noaa.gov/NARR/197903/197903 |
| ftp://nomads.ncdc.noaa.gov/NARR/197904/197904 |
| ftp://nomads.ncdc.noaa.gov/NARR/197905/197905 |
| ftp://nomads.ncdc.noaa.gov/NARR/197906/197906 |

Write the URLs to a file for wget to read.

#+BEGIN_SRC R :session *R* :results silent
  cat( urls, file= "urls", sep= "\n")  
#+END_SRC

Files since 201208 do not have monthly subfolders.

#+BEGIN_SRC R :session *R* :results silent
  
  narrDays <-
    seq(
      as.Date( "2012-11-30"),
      as.Date( "2012-12-08"),
      by= "day")
  
  urls <- paste(
    baseUrl,
    format( narrDays, "%Y%m"),
    format( narrDays, "%Y%m%d"),
    sep= "/")
#+END_SRC

Examine a sample of the resulting URLs.

#+BEGIN_SRC R :session *R*
  urls
#+END_SRC

#+RESULTS:
| ftp://nomads.ncdc.noaa.gov/NARR/201211/20121130 |
| ftp://nomads.ncdc.noaa.gov/NARR/201212/20121201 |
| ftp://nomads.ncdc.noaa.gov/NARR/201212/20121202 |
| ftp://nomads.ncdc.noaa.gov/NARR/201212/20121203 |
| ftp://nomads.ncdc.noaa.gov/NARR/201212/20121204 |
| ftp://nomads.ncdc.noaa.gov/NARR/201212/20121205 |
| ftp://nomads.ncdc.noaa.gov/NARR/201212/20121206 |
| ftp://nomads.ncdc.noaa.gov/NARR/201212/20121207 |
| ftp://nomads.ncdc.noaa.gov/NARR/201212/20121208 |

Write the URLs to a file for wget to read.

#+BEGIN_SRC R :session *R* :results silent
  cat(
    urls, file= "urls",
    sep= "\n", append= FALSE)  
#+END_SRC


#+BEGIN_SRC sh
  screen -d -m -S narr
  screen -S narr -X zombie ko
  screen -S narr -X screen \
      wget  --no-verbose --recursive --no-clobber --retr-symlinks \
      --force-directories --no-host-directories --directory-prefix /project/joshuaelliott/narr/data/grb --cut-dirs=2 \
      --input-file=/project/joshuaelliott/narr/urls --accept "narr-a*.grb"
#+END_SRC

#+RESULTS:

After 201208 there are no monthly folders on the server so we have to
move some files around to get a uniform directory structure.

#+BEGIN_SRC sh
  mkdir -v data/grb/2012{09,10,11,12}
  find data/grb -regex 'data/grb/2012\(09\|1[012]\)../.*?grb$' > dailyDirs.txt
  perl -ne 'chomp; m#^(data/grb/2012..)#; print "mv $_ $1\n";' dailyDirs.txt | bash
  find data/grb -type d -empty -delete
  rm dailyDirs.txt 
#+END_SRC

Make a list of all .grb input files for Swift initialization.

#+BEGIN_SRC sh :results silent
find data/grb -type f -name *.grb | sort > grbFiles.txt
#+END_SRC

#+BEGIN_SRC sh :results silent :eval no
find data/grb/20121{1,2} -type f -name *.grb | sort > grbFiles.txt
#+END_SRC

* Identify the variables of interest

#+NAME:variables
#+BEGIN_SRC sh :session *ssh-midway* :results output raw
  echo "|band|name|height|description|"
  echo "|-"
  egrep "^(288|380|389|406)" data/197901/narr-a_221_19790101_0000_000.inv | cut -d: -f 1,4,5,9 | perl -pe 's/:"?/|/g; s/^/|/; s/$/|/'
#+END_SRC

#+RESULTS: variables
| band | name  | height        | description                               |
|------+-------+---------------+-------------------------------------------|
|  288 | TMP   | 2 m above gnd | Temp. [K]                                 |
|  380 | APCP  | sfc           | Total precipitation [kg/m^2]              |
|  389 | CRAIN | sfc           | Categorical rain [yes=1;no=0]             |
|  406 | DSWRF | sfc           | Downward shortwave radiation flux [W/m^2] |



* Perform the transformation manually to get it right
** TODO Create/test remote directories
   grb2, nc

** Convert to GRIB2 format

#+BEGIN_SRC sh :dir /midway:/project/joshuaelliott/narr
  mkdir -p data/grb2/197901
  for hour in 00 03 06 09 12 15 18 21; do
        cnvgrib -g12 -nv \
            data/grb/197901/narr-a_221_19790101_${hour}00_000.grb \
            data/grb2/197901/narr-a_221_19790101_${hour}00_000.grb2
  done  
#+END_SRC

#+RESULTS:

** Extract the variables of interest

#+BEGIN_SRC sh :results silent :dir /midway:/project/joshuaelliott/narr
  mkdir -p data/nc/197901
  for hour in 00 03 06 09 12 15 18 21; do
      wgrib2 data/grb2/197901/narr-a_221_19790101_${hour}00_000.grb2 \
          -match ':(TMP:2 m|APCP:|CRAIN:|DSWRF:)' \
          -new_grid_winds earth -new_grid_interpolation neighbor \
          -new_grid latlon 220.041666666666:960:0.083333333333 20.041666666666:480:0.0833333333333 - \
          | wgrib2 - -order we:sn -nc3 -nc_table nc_table \
          -netcdf data/nc/197901/narr-a_221_19790101_${hour}00_000.nc
  done
  
#+END_SRC

Can use '-set_ext_name 0' instead of -nc_table.

** Get rid of the empty second time step added by wgrib2

#+BEGIN_SRC sh :session *ssh-midway*
  cdo seltimestep,1 \
      data/nc/197901/narr-a_221_19790101_0000_000.nc \
      data/nc/197901/narr-a_221_19790101_0000_000.single.nc
#+END_SRC

** Merge and aggregate

*** Merge into an annual file

#+BEGIN_SRC sh :session *shell* :results output verbatim
  cdo -O mergetime \
      $(find data/nc/1979* -type f -name narr-a_221_*00_000.single.nc) \
      data/nc/annual/1979.nc
#+END_SRC

#+RESULTS:
: 
: > cdo mergetime: Processed 5382144000 values from 11680 variables over 2920 timesteps ( 127.04s )

Do the same through SLURM.

#+BEGIN_SRC sh :session *shell* :results output verbatim
  srun --partition=westmere --immediate=3600 cdo -O mergetime \
      $(find data/nc/1980* -type f -name narr-a_221_*00_000.single.nc) \
      data/nc/annual/1980.nc
#+END_SRC

#+BEGIN_SRC sh :session *shell* :results output verbatim
  for year in {1981..2012}; do
      srun --partition=westmere --immediate=3600 cdo mergetime \
          $(find data/nc/${year}* -type f -name narr-a_221_*00_000.single.nc) \
          data/nc/annual/${year}.nc &
  done
#+END_SRC

#+RESULTS:
#+begin_example

> > > [2] 7186
[3] 7187
[4] 7188
[5] 7190
[6] 7192
[7] 7194
[8] 7196
[9] 7198
[10] 7200
[11] 7202
[12] 7204
[13] 7206
[14] 7208
[15] 7210
[16] 7212
[17] 7214
[18] 7215
[19] 7218
[20] 7220
[21] 7222
[22] 7224
[23] 7226
[24] 7228
[25] 7230
[26] 7231
[27] 7234
[28] 7238
[29] 7240
[30] 7242
[31] 7244
[32] 7246
[33] 7248
#+end_example


*** Aggregate

#+BEGIN_SRC sh :session *ssh-midway* :results output verbatim
  cdo daymin -selname,TMP data/nc/197901.nc data/nc/197901_tmin.nc
  cdo daymax -selname,TMP data/nc/197901.nc data/nc/197901_tmax.nc
  cdo daysum -selname,APCP data/nc/197901.nc data/nc/197901_precip.nc
  cdo daymean -selname,DSWRF data/nc/197901.nc data/nc/197901_solar.nc
#+END_SRC

#+RESULTS:
#+begin_example
cdo daymin: Started child process "selname,TMP data/nc/197901.nc (pipe1.1)".
cdo(2) selname: Processed 114278400 values from 4 variables over 248 timesteps ( 2.86s )
cdo daymin: Processed 114278400 values from 1 variable over 248 timesteps ( 2.86s )
cdo daymax: Started child process "selname,TMP data/nc/197901.nc (pipe1.1)".
cdo(2) selname: Processed 114278400 values from 4 variables over 248 timesteps ( 2.96s )
cdo daymax: Processed 114278400 values from 1 variable over 248 timesteps ( 2.96s )
cdo daysum: Started child process "selname,APCP data/nc/197901.nc (pipe1.1)".
cdo(2) selname: Processed 114278400 values from 4 variables over 248 timesteps ( 4.83s )
cdo daysum: Processed 114278400 values from 1 variable over 248 timesteps ( 4.83s )
cdo daymean: Started child process "selname,DSWRF data/nc/197901.nc (pipe1.1)".
cdo(2) selname: Processed 114278400 values from 4 variables over 248 timesteps ( 5.12s )
cdo daymean: Processed 114278400 values from 1 variable over 248 timesteps ( 5.12s )
#+end_example


** Testing remote execution

#+BEGIN_SRC sh :dir /midway:~
echo "Executed by `whoami` on `hostname` in `pwd`"
#+END_SRC

#+RESULTS:
: Executed by nbest on lep in /Users/nbest

#+BEGIN_SRC sh :session *ssh-midway*
echo "Executed by `whoami` on `hostname` in `pwd`"
#+END_SRC

#+RESULTS:
: Executed by nbest on midway-login1 in /project/joshuaelliott/narr


#+BEGIN_SRC sh :session *shell* :results output verbatim
echo "Executed by `whoami` on `hostname` in `pwd`"
module list 2>&1
which cdo
#+END_SRC


#+RESULTS:
#+begin_example
Executed by nbest on midway-login1 in /project/joshuaelliott/narr
Currently Loaded Modulefiles:
 1) slurm/2.4      
 2) vim/7.3        
 3) subversion/1.6 
 4) env/rcc        
 5) git/1.7        
 6) R/2.15         
 7) hdf5/1.8       
 8) netcdf/4.2     
 9) postgresql/9.2 
10) proj/4.8       
11) gdal/1.9       
12) jasper/1.900   
13) cnvgrib/1.4    
14) wgrib2/0.1     
15) texinfo/4.13a  
16) texlive/2012   
17) grib_api/1.9   
18) cdo/1.5        
19) java/1.7       
20) emacs/23.4
/software/cdo-1.5-el6-x86_64/bin/cdo
#+end_example

#+BEGIN_SRC sh :results output verbatim
echo "Executed by `whoami` on `hostname` in `pwd`"
module list 2>&1
which cdo
#+END_SRC

#+RESULTS:

** Processing errors

Running the stage that copies the first time step of the wgrib2
output to the *.single.nc files produced 22 errors.  

#+NAME: swiftErrors
#+BEGIN_EXAMPLE
1. Exception in cdo:
    Arguments: [seltimestep,1, data/nc/200505/narr-a_221_20050523_0000_000.nc, data/nc/200505/narr-a_221_20050523_0000_000.single.nc]
    Host: cluster
    Directory: narr-20121205-0003-agtvuf28/jobs/7/cdo-7cieex1l
    stderr.txt: cdo seltimestep: Open failed on >data/nc/200505/narr-a_221_20050523_0000_000.nc<
Unsupported file type
    stdout.txt:
Caused by:
        The following output files were not created by the application: data/nc/200505/narr-a_221_20050523_0000_000.single.nc
2. Exception in cdo:
    Arguments: [seltimestep,1, data/nc/200509/narr-a_221_20050922_2100_000.nc, data/nc/200509/narr-a_221_20050922_2100_000.single.nc]
    Host: cluster
    Directory: narr-20121205-0003-agtvuf28/jobs/k/cdo-k37eex1l
Caused by:
        File not found: /project/joshuaelliott/narr/./data/nc/200509/narr-a_221_20050922_2100_000.nc
3. Exception in cdo:
    Arguments: [seltimestep,1, data/nc/200605/narr-a_221_20060503_0000_000.nc, data/nc/200605/narr-a_221_20060503_0000_000.single.nc]
    Host: cluster
    Directory: narr-20121205-0003-agtvuf28/jobs/a/cdo-a3aeex1l
Caused by:
        File not found: /project/joshuaelliott/narr/./data/nc/200605/narr-a_221_20060503_0000_000.nc
4. Exception in cdo:
    Arguments: [seltimestep,1, data/nc/200403/narr-a_221_20040326_0000_000.nc, data/nc/200403/narr-a_221_20040326_0000_000.single.nc]
    Host: cluster
    Directory: narr-20121205-0003-agtvuf28/jobs/i/cdo-irceex1l
Caused by:
        File not found: /project/joshuaelliott/narr/./data/nc/200403/narr-a_221_20040326_0000_000.nc
5. Exception in cdo:
    Arguments: [seltimestep,1, data/nc/200505/narr-a_221_20050524_0900_000.nc, data/nc/200505/narr-a_221_20050524_0900_000.single.nc]
    Host: cluster
    Directory: narr-20121205-0003-agtvuf28/jobs/m/cdo-mfieex1l
    stderr.txt: cdo seltimestep: Open failed on >data/nc/200505/narr-a_221_20050524_0900_000.nc<
Unsupported file type
    stdout.txt:
Caused by:
        The following output files were not created by the application: data/nc/200505/narr-a_221_20050524_0900_000.single.nc
6. Exception in cdo:
    Arguments: [seltimestep,1, data/nc/200505/narr-a_221_20050527_0300_000.nc, data/nc/200505/narr-a_221_20050527_0300_000.single.nc]
    Host: cluster
    Directory: narr-20121205-0003-agtvuf28/jobs/7/cdo-7eieex1l
    stderr.txt: cdo seltimestep: Open failed on >data/nc/200505/narr-a_221_20050527_0300_000.nc<
Unsupported file type
    stdout.txt:
Caused by:
        The following output files were not created by the application: data/nc/200505/narr-a_221_20050527_0300_000.single.nc
7. Exception in cdo:
    Arguments: [seltimestep,1, data/nc/200506/narr-a_221_20050610_1200_000.nc, data/nc/200506/narr-a_221_20050610_1200_000.single.nc]
    Host: cluster
    Directory: narr-20121205-0003-agtvuf28/jobs/z/cdo-z7ieex1l
    stderr.txt: cdo seltimestep: Open failed on >data/nc/200506/narr-a_221_20050610_1200_000.nc<
Unsupported file type
    stdout.txt:
Caused by:
        The following output files were not created by the application: data/nc/200506/narr-a_221_20050610_1200_000.single.nc
8. Exception in cdo:
    Arguments: [seltimestep,1, data/nc/200505/narr-a_221_20050516_0600_000.nc, data/nc/200505/narr-a_221_20050516_0600_000.single.nc]
    Host: cluster
    Directory: narr-20121205-0003-agtvuf28/jobs/s/cdo-sbieex1l
    stderr.txt: cdo seltimestep: Open failed on >data/nc/200505/narr-a_221_20050516_0600_000.nc<
Unsupported file type
    stdout.txt:
Caused by:
        The following output files were not created by the application: data/nc/200505/narr-a_221_20050516_0600_000.single.nc
9. Exception in cdo:
    Arguments: [seltimestep,1, data/nc/200603/narr-a_221_20060304_0000_000.nc, data/nc/200603/narr-a_221_20060304_0000_000.single.nc]
    Host: cluster
    Directory: narr-20121205-0003-agtvuf28/jobs/j/cdo-jz8eex1l
Caused by:
        File not found: /project/joshuaelliott/narr/./data/nc/200603/narr-a_221_20060304_0000_000.nc
10. Exception in cdo:
    Arguments: [seltimestep,1, data/nc/200506/narr-a_221_20050615_0900_000.nc, data/nc/200506/narr-a_221_20050615_0900_000.single.nc]
    Host: cluster
    Directory: narr-20121205-0003-agtvuf28/jobs/n/cdo-n8ieex1l
    stderr.txt: cdo seltimestep: Open failed on >data/nc/200506/narr-a_221_20050615_0900_000.nc<
Unsupported file type
    stdout.txt:
Caused by:
        The following output files were not created by the application: data/nc/200506/narr-a_221_20050615_0900_000.single.nc
11. Exception in cdo:
    Arguments: [seltimestep,1, data/nc/200505/narr-a_221_20050531_2100_000.nc, data/nc/200505/narr-a_221_20050531_2100_000.single.nc]
    Host: cluster
    Directory: narr-20121205-0003-agtvuf28/jobs/s/cdo-sfieex1l
    stderr.txt: cdo seltimestep: Open failed on >data/nc/200505/narr-a_221_20050531_2100_000.nc<
Unsupported file type
    stdout.txt:
Caused by:
        The following output files were not created by the application: data/nc/200505/narr-a_221_20050531_2100_000.single.nc
12. Exception in cdo:
    Arguments: [seltimestep,1, data/nc/200507/narr-a_221_20050709_0000_000.nc, data/nc/200507/narr-a_221_20050709_0000_000.single.nc]
    Host: cluster
    Directory: narr-20121205-0003-agtvuf28/jobs/r/cdo-riieex1l
    stderr.txt: cdo seltimestep: Open failed on >data/nc/200507/narr-a_221_20050709_0000_000.nc<
Unsupported file type
    stdout.txt:
Caused by:
        The following output files were not created by the application: data/nc/200507/narr-a_221_20050709_0000_000.single.nc
13. Exception in cdo:
    Arguments: [seltimestep,1, data/nc/200603/narr-a_221_20060308_0000_000.nc, data/nc/200603/narr-a_221_20060308_0000_000.single.nc]
    Host: cluster
    Directory: narr-20121205-0003-agtvuf28/jobs/9/cdo-919eex1l
Caused by:
        File not found: /project/joshuaelliott/narr/./data/nc/200603/narr-a_221_20060308_0000_000.nc
14. Exception in cdo:
    Arguments: [seltimestep,1, data/nc/200506/narr-a_221_20050616_2100_000.nc, data/nc/200506/narr-a_221_20050616_2100_000.single.nc]
    Host: cluster
    Directory: narr-20121205-0003-agtvuf28/jobs/v/cdo-v8ieex1l
    stderr.txt: cdo seltimestep: Open failed on >data/nc/200506/narr-a_221_20050616_2100_000.nc<
Unsupported file type
    stdout.txt:
Caused by:
        The following output files were not created by the application: data/nc/200506/narr-a_221_20050616_2100_000.single.nc
15. Exception in cdo:
    Arguments: [seltimestep,1, data/nc/200506/narr-a_221_20050613_2100_000.nc, data/nc/200506/narr-a_221_20050613_2100_000.single.nc]
    Host: cluster
    Directory: narr-20121205-0003-agtvuf28/jobs/e/cdo-e9ieex1l
    stderr.txt: cdo seltimestep: Open failed on >data/nc/200506/narr-a_221_20050613_2100_000.nc<
Unsupported file type
    stdout.txt:
Caused by:
        The following output files were not created by the application: data/nc/200506/narr-a_221_20050613_2100_000.single.nc
16. Exception in cdo:
    Arguments: [seltimestep,1, data/nc/200506/narr-a_221_20050616_0600_000.nc, data/nc/200506/narr-a_221_20050616_0600_000.single.nc]
    Host: cluster
    Directory: narr-20121205-0003-agtvuf28/jobs/6/cdo-69ieex1l
    stderr.txt: cdo seltimestep: Open failed on >data/nc/200506/narr-a_221_20050616_0600_000.nc<
Unsupported file type
    stdout.txt:
Caused by:
        The following output files were not created by the application: data/nc/200506/narr-a_221_20050616_0600_000.single.nc
17. Exception in cdo:
    Arguments: [seltimestep,1, data/nc/200505/narr-a_221_20050526_0000_000.nc, data/nc/200505/narr-a_221_20050526_0000_000.single.nc]
    Host: cluster
    Directory: narr-20121205-0003-agtvuf28/jobs/l/cdo-leieex1l
    stderr.txt: cdo seltimestep: Open failed on >data/nc/200505/narr-a_221_20050526_0000_000.nc<
Unsupported file type
    stdout.txt:
Caused by:
        The following output files were not created by the application: data/nc/200505/narr-a_221_20050526_0000_000.single.nc
18. Exception in cdo:
    Arguments: [seltimestep,1, data/nc/200506/narr-a_221_20050609_0300_000.nc, data/nc/200506/narr-a_221_20050609_0300_000.single.nc]
    Host: cluster
    Directory: narr-20121205-0003-agtvuf28/jobs/s/cdo-s7ieex1l
    stderr.txt: cdo seltimestep: Open failed on >data/nc/200506/narr-a_221_20050609_0300_000.nc<
Unsupported file type
    stdout.txt:
Caused by:
        The following output files were not created by the application: data/nc/200506/narr-a_221_20050609_0300_000.single.nc
19. Exception in cdo:
    Arguments: [seltimestep,1, data/nc/200506/narr-a_221_20050615_0000_000.nc, data/nc/200506/narr-a_221_20050615_0000_000.single.nc]
    Host: cluster
    Directory: narr-20121205-0003-agtvuf28/jobs/t/cdo-t8ieex1l
    stderr.txt: cdo seltimestep: Open failed on >data/nc/200506/narr-a_221_20050615_0000_000.nc<
Unsupported file type
    stdout.txt:
Caused by:
        The following output files were not created by the application: data/nc/200506/narr-a_221_20050615_0000_000.single.nc
20. Exception in cdo:
    Arguments: [seltimestep,1, data/nc/200506/narr-a_221_20050613_0600_000.nc, data/nc/200506/narr-a_221_20050613_0600_000.single.nc]
    Host: cluster
    Directory: narr-20121205-0003-agtvuf28/jobs/k/cdo-k9ieex1l
    stderr.txt: cdo seltimestep: Open failed on >data/nc/200506/narr-a_221_20050613_0600_000.nc<
Unsupported file type
    stdout.txt:
Caused by:
        The following output files were not created by the application: data/nc/200506/narr-a_221_20050613_0600_000.single.nc
21. Exception in cdo:
    Arguments: [seltimestep,1, data/nc/200505/narr-a_221_20050529_1500_000.nc, data/nc/200505/narr-a_221_20050529_1500_000.single.nc]
    Host: cluster
    Directory: narr-20121205-0003-agtvuf28/jobs/r/cdo-rgieex1l
    stderr.txt: cdo seltimestep: Open failed on >data/nc/200505/narr-a_221_20050529_1500_000.nc<
Unsupported file type
    stdout.txt:
Caused by:
        The following output files were not created by the application: data/nc/200505/narr-a_221_20050529_1500_000.single.nc
22. Exception in cdo:
    Arguments: [seltimestep,1, data/nc/200506/narr-a_221_20050614_1800_000.nc, data/nc/200506/narr-a_221_20050614_1800_000.single.nc]
    Host: cluster
    Directory: narr-20121205-0003-agtvuf28/jobs/s/cdo-s9ieex1l
    stderr.txt: cdo seltimestep: Open failed on >data/nc/200506/narr-a_221_20050614_1800_000.nc<
Unsupported file type
    stdout.txt:
Caused by:
        The following output files were not created by the application: data/nc/200506/narr-a_221_20050614_1800_000.single.nc
#+END_EXAMPLE

*** TODO Report Org-mode bug of lost line termination

        File not found: /project/joshuaelliott/narr/./data/nc/200509/narr-a_221_20050922_2100_000.nc

#+NAME: filterBadFiles
#+BEGIN_SRC sh :value verbatim output
  ( \
      perl -ne 'print "$1\n" if m#File not found: /project/joshuaelliott/narr/./([^\s]+)$#' swiftErrors.txt && \
      perl -ne 'print "$1\n" if />([^<]+)</' swiftErrors.txt ) | sort  
#+END_SRC


#+RESULTS: filterBadFiles
| data/nc/200403/narr-a_221_20040326_0000_000.nc |
| data/nc/200505/narr-a_221_20050516_0600_000.nc |
| data/nc/200505/narr-a_221_20050523_0000_000.nc |
| data/nc/200505/narr-a_221_20050524_0900_000.nc |
| data/nc/200505/narr-a_221_20050526_0000_000.nc |
| data/nc/200505/narr-a_221_20050527_0300_000.nc |
| data/nc/200505/narr-a_221_20050529_1500_000.nc |
| data/nc/200505/narr-a_221_20050531_2100_000.nc |
| data/nc/200506/narr-a_221_20050609_0300_000.nc |
| data/nc/200506/narr-a_221_20050610_1200_000.nc |
| data/nc/200506/narr-a_221_20050613_0600_000.nc |
| data/nc/200506/narr-a_221_20050613_2100_000.nc |
| data/nc/200506/narr-a_221_20050614_1800_000.nc |
| data/nc/200506/narr-a_221_20050615_0000_000.nc |
| data/nc/200506/narr-a_221_20050615_0900_000.nc |
| data/nc/200506/narr-a_221_20050616_0600_000.nc |
| data/nc/200506/narr-a_221_20050616_2100_000.nc |
| data/nc/200507/narr-a_221_20050709_0000_000.nc |
| data/nc/200509/narr-a_221_20050922_2100_000.nc |
| data/nc/200603/narr-a_221_20060304_0000_000.nc |
| data/nc/200603/narr-a_221_20060308_0000_000.nc |
| data/nc/200605/narr-a_221_20060503_0000_000.nc |


Some of these were due to empty .nc files.

#+NAME: emptyNc
#+BEGIN_SRC sh
find data/nc -size 0 | sort
#+END_SRC

#+RESULTS: emptyNc
| data/nc/200505/narr-a_221_20050516_0600_000.nc |
| data/nc/200505/narr-a_221_20050523_0000_000.nc |
| data/nc/200505/narr-a_221_20050524_0900_000.nc |
| data/nc/200505/narr-a_221_20050526_0000_000.nc |
| data/nc/200505/narr-a_221_20050527_0300_000.nc |
| data/nc/200505/narr-a_221_20050529_1500_000.nc |
| data/nc/200505/narr-a_221_20050531_2100_000.nc |
| data/nc/200506/narr-a_221_20050609_0300_000.nc |
| data/nc/200506/narr-a_221_20050610_1200_000.nc |
| data/nc/200506/narr-a_221_20050613_0600_000.nc |
| data/nc/200506/narr-a_221_20050613_2100_000.nc |
| data/nc/200506/narr-a_221_20050614_1800_000.nc |
| data/nc/200506/narr-a_221_20050615_0000_000.nc |
| data/nc/200506/narr-a_221_20050615_0900_000.nc |
| data/nc/200506/narr-a_221_20050616_0600_000.nc |
| data/nc/200506/narr-a_221_20050616_2100_000.nc |
| data/nc/200507/narr-a_221_20050709_0000_000.nc |


Use this list to write a new list of .grb files to initialize Swift.


#+NAME grbFiles
#+BEGIN_SRC sh :noweb yes
<<filterBadFiles>>  | perl -pe "s/nc/grb/g" | tee grbFilesRedo.txt
#+END_SRC

#+RESULTS:
| data/grb/200403/narr-a_221_20040326_0000_000.grb |
| data/grb/200505/narr-a_221_20050516_0600_000.grb |
| data/grb/200505/narr-a_221_20050523_0000_000.grb |
| data/grb/200505/narr-a_221_20050524_0900_000.grb |
| data/grb/200505/narr-a_221_20050526_0000_000.grb |
| data/grb/200505/narr-a_221_20050527_0300_000.grb |
| data/grb/200505/narr-a_221_20050529_1500_000.grb |
| data/grb/200505/narr-a_221_20050531_2100_000.grb |
| data/grb/200506/narr-a_221_20050609_0300_000.grb |
| data/grb/200506/narr-a_221_20050610_1200_000.grb |
| data/grb/200506/narr-a_221_20050613_0600_000.grb |
| data/grb/200506/narr-a_221_20050613_2100_000.grb |
| data/grb/200506/narr-a_221_20050614_1800_000.grb |
| data/grb/200506/narr-a_221_20050615_0000_000.grb |
| data/grb/200506/narr-a_221_20050615_0900_000.grb |
| data/grb/200506/narr-a_221_20050616_0600_000.grb |
| data/grb/200506/narr-a_221_20050616_2100_000.grb |
| data/grb/200507/narr-a_221_20050709_0000_000.grb |
| data/grb/200509/narr-a_221_20050922_2100_000.grb |
| data/grb/200603/narr-a_221_20060304_0000_000.grb |
| data/grb/200603/narr-a_221_20060308_0000_000.grb |
| data/grb/200605/narr-a_221_20060503_0000_000.grb |


* Fake extra data to finish the time series

This approach was flawed because the metadata within the linked files
will throw off the subsequent steps, i.e. cdo mergetime.

#+BEGIN_SRC R :session *R* :eval no
  
  ## file.symlink(
  ##   to= "data/nc/201212/narr-a_221_20121231_2100_000.1.nc",
  ##   from="data/nc/201112/narr-a_221_20111231_2100_000.1.nc")
  
  fakeThreeHours <-
    seq(
      ISOdate( 2012,12,9, hour= 0),
      ISOdate( 2012,12,31, hour= 21),    
      by= "3 hours")
  
  oneYearEarlier <- {
    foo <- as.POSIXlt( fakeThreeHours)
    foo$year <- foo$year -1
    as.POSIXct( foo)
  }
  
  pathToTimeStep <- function( date, step) {
    sprintf(
      "%s/narr-a_221_%s_000.%d.nc",
      format( date, "%Y%m"),
      format( date, "%Y%m%d_%H%M"),
      step)
  }
  
  linkTo <-
    paste(
      "data/nc",
      c(
        pathToTimeStep( fakeThreeHours, 1),
        pathToTimeStep( fakeThreeHours, 2)),
      sep= "/")
  
  linkFrom <-
    paste(
      "..",
      c(
        pathToTimeStep( oneYearEarlier, 1),
        pathToTimeStep( oneYearEarlier, 2)),
      sep= "/")
  
  ## head( cbind( linkTo, linkFrom))
  ## tail( cbind( linkTo, linkFrom))
  
  file.symlink(
    to=   linkTo,
    from= linkFrom)
  
  
#+END_SRC

#+BEGIN_SRC R :session *R*
  
  fakeThreeHours <-
    seq(
      ISOdate( 2012,12,9, hour= 0),
      ISOdate( 2012,12,31, hour= 21),    
      by= "3 hours")
  
  oneYearEarlier <- {
    foo <- as.POSIXlt( fakeThreeHours)
    foo$year <- foo$year -1
    as.POSIXct( foo)
  }
  
  pathToTimeStep <- function( date, step) {
    sprintf(
      "%s/narr-a_221_%s_000.%d.nc",
      format( date, "%Y%m"),
      format( date, "%Y%m%d_%H%M"),
      step)
  }
  
  outFile <-
    paste(
      "data/nc",
      c(
        pathToTimeStep( fakeThreeHours, 1),
        pathToTimeStep( fakeThreeHours, 2)),
      sep= "/")
  
  inFile <-
    paste(
      "data/nc",
      c(
        pathToTimeStep( oneYearEarlier, 1),
        pathToTimeStep( oneYearEarlier, 2)),
      sep= "/")
  
  
  cat( inFile, file="oneYearEarlier.txt", sep= "\n")
#+END_SRC


